### ISSUE TITLE
Links in outline do nothing when left clicked in Joplin v1.6.6

### ISSUE THREAD

**Issue by DawMatt** [cqroot/joplin-outline#10]
I've recently installed Joplin 1.6.5, then 1.6.6, to try to work around recent syncing issues.

When I've used the Outline plugin with this version the Outline no longer seems to work. I'm sure it behaved differently when I was using the 1.5.4 version. In 1.6.x the outline displays as usual and hovering over an element in the outline does visually change into a link, but left clicking on a link does nothing. Right clicking on the link does bring up the "inner link has been copied" dialog for the link under the cursor.

I've tested this on both the Windows and Mac native versions of Joplin and the result is the same. See the screenshot below for an example note I created to test the issue. There are 10 sub-headings all with the same content to make sure the last headings would be at least 2 screens below heading 1. Clicking on the links for Sub-headings 9 or 10 (for example) results in no movement of the editor view, regardless of where the cursor is at the time I click the outline link.
![image](https://user-images.githubusercontent.com/476705/104137861-08d16b80-53f4-11eb-8db4-492df7f85f8b.png)

**Comment by jahoyne** [comment]
Here also experiencing the same as @DawMatt. Outline plugin working in 1.5.4, but not in 1.6.6

**Comment by cqroot** [comment]
Joplin 1.6.7 fixed it.
