### ISSUE TITLE
Richtext editor support

### ISSUE THREAD

**Issue by JOJ0** [cqroot/joplin-outline#11]
Hi, just a question: Do you think it is possible to make this plugin compatible with the richtext editor? Or is this a general "not compatible at all" issue?
thanks!
Jojo

**Comment by cqroot** [comment]
Did you mean the wysiwyg editor? As the wysiwyg editor is not very mature, I have not used it currently. It may be compatible in the future.

**Comment by JOJ0** [comment]
yeah exactely. i think it's called rich text editor in joplin's options IIRC.
thanks in advance and let me know. for now this issue could be closed.
