### ISSUE TITLE
Outline plugin picks up commented out headings to display in the panel

### ISSUE THREAD

**Issue by asheeshr** [cqroot/joplin-outline#16]
I am trying out the plugin. It's useful as it allows at a glance to see what the note contents are even if you're editing somewhere deep in the note which is great! 

I noticed this bug that when my note contains the following block:
```
<!--
### Thing

-->
```

This is the ```[toc]``` output:

![Screenshot from 2021-01-18 16-49-11](https://user-images.githubusercontent.com/1908945/104965690-42364800-59ad-11eb-80cb-0d25f1c18de8.png)

This is the outline plugin output:
![Screenshot from 2021-01-18 16-49-16](https://user-images.githubusercontent.com/1908945/104965687-42364800-59ad-11eb-9bbe-a7ed772277b9.png)

Those two should be identical.

**Comment by cqroot** [comment]
1.0.9 fixed it.
