### ISSUE TITLE
Recent update = big left margin 

### ISSUE THREAD

**Issue by jt196** [cqroot/joplin-outline#20]
![image](https://user-images.githubusercontent.com/8290163/106354960-33289180-62ed-11eb-869d-fcc57f1b3818.png)

Probably best explained with a picture - updated the plugin today and the left margin is way too big.

**Comment by cqroot** [comment]
An unknown bug led to a new plugin panel. The problem disappeared after trying to reload the plugin.

**Comment by jt196** [comment]
Correct, I disabled, restarted, enabled and restarted and it's working again. Kinda annoying I have to resize the panel again, but I guess that's a Joplin thing.

**Comment by soharang** [comment]
Setting > Appearance > Set `Editor maximum width` as 0.
