### ISSUE TITLE
Right click on outline item breaks it

### ISSUE THREAD

**Issue by jt196** [cqroot/joplin-outline#21]
If I right click on any of the links, the plugin crashes - I can't click on any of the links, the outline then stays the same even if I move to a new note.

**Comment by cqroot** [comment]
Provide your system information, joplin version and plugin version.
I tried it and it was normal. Right-clicking will pop up a message box saying that the inner link has been copied successfully.

**Comment by jt196** [comment]
Sorry mate should have done that right away.

MacOS Big Sur 11.1

---

Joplin 1.7.11 (prod, darwin)

Client ID: 1dc40a51b7834ffc8ac385f2509a2e6b
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563 (master)

---

v1.1.0

**Comment by jt196** [comment]
So I updated it from the previous version and what I've noticed is that the window does pop up, but it's virtually hidden above the user interface. It may have been there before I updated it but I didn't notice it. 

![image](https://user-images.githubusercontent.com/8290163/107202252-e54d1100-69f1-11eb-98f2-cc5ba8fccb86.png)

**Comment by jt196** [comment]
So, moving the main window around helped a little bit: 

![image](https://user-images.githubusercontent.com/8290163/107207747-96ef4080-69f8-11eb-9548-659d905b297c.png)

If I rotate the screen 90 degrees, I can see the full window but it's hovering above the main window. I can't move the pop up window though. 

The pop up window also isn't part of the Joplin window on Mission Control, so four finger swipe down on the trackpad (shows all windows of active app) doesn't show the pop up. I've tried a bunch of methods to move the window (Accessibility for example), they move the Joplin window but not the pop up.

**Comment by cqroot** [comment]
I will cancel the pop-up of the message box in the next version. Maybe I will use other methods to tell the user that the paste is complete.

**Comment by jt196** [comment]
OK - just updated to the most recent version and it seems like the pop-up has gone, but doesn't look like the toc URL is copied to the clipboard either.

**Comment by cqroot** [comment]
Not yet, the last few updates are for other issues. I am exploring other ways to notify users and testing under MacOS. I will tell you after the feature is added and close this issue. It will be completed in two days.

**Comment by jt196** [comment]
Ah cool - no rush! Just trying to help get it working!

**Comment by jt196** [comment]
@cqroot looks like it's working well now! Like the simplicity of the heading changing. Good work. 

FYI the correct English for the message should be either "Copy Successful!" (noun + adjective) or "Copied Successfully!" (verb participle + adverb). I'd probably go with the former as it's simpler and cleaner. Cheers!

**Comment by cqroot** [comment]
Oh, thanks for reminding.
