### ISSUE TITLE
feature request - Please add a show/hide button

### ISSUE THREAD

**Issue by netfly** [cqroot/joplin-outline#22]
Awesome plugin, but it whould be nice to have a show/hide button.

Thanks
Markus

**Comment by netfly** [comment]
awesome ... thank you

**Comment by cqroot** [comment]
1.1.3 version now supports toggling panel display.

When the panel is on the far right, there will be a bug that only hides the content of the panel. It is recommended to put the outline panel on the left side of the note. 

https://discourse.joplinapp.org/t/how-to-switch-the-display-and-hide-of-the-plugin-panel/13479
