### ISSUE TITLE
Outline bar width remains fixed if Joplin window is resized

### ISSUE THREAD

**Issue by MirceaDavidEsc** [cqroot/joplin-outline#27]
In Windows 10, when I have the outline open and I resize the Joplin window's width, the editor and Markdown preview panels end up locked at the same width while the outline panel ends up expanding to fill the width.
For instance, starting with one width
![image](https://user-images.githubusercontent.com/6342462/109444843-2aba9800-7a0c-11eb-80ba-ec14d7b0de29.png)

Expanding the window causes the Outline panel to expand, while the other panels remain at a fixed width
![image](https://user-images.githubusercontent.com/6342462/109444921-5b9acd00-7a0c-11eb-9452-762d3571c4d1.png)

This seems like unexpected behavior. I think if the window resizes, the user would expect the **relative** widths of the panels to stay the same. For instance if the Joplin window is 1,000px in diameter my editor is 40% (400px), my preview is 40% (400px), and the outline is 20% (200px), and then I resize the window to 2,000px, I would want me new widths to be 800-800-400, rather than 400-400-1200px.

**Comment by cqroot** [comment]
https://github.com/cqroot/joplin-outline/issues/9
https://github.com/laurent22/joplin/issues/4238

It is recommended to put the outline on the left side of the note.

**Comment by MirceaDavidEsc** [comment]
Are there instructions on how to move it? I cannot find the option in either the settings or by clicking around in the menu.
