### ISSUE TITLE
Add font resize button in the sidebar

### ISSUE THREAD

**Issue by Gushka** [cqroot/joplin-outline#3]
## The issue
Default font size in the sidebar is too small for me, it would be great if it could be changed for the user's liking.
Also, for users with high-resolution monitors and those that use Joplin in the fullscreen mode this would be very helpful and easy on their eyes.

## Demonstration:

I'm using Joplin 1.5.12 on Windows 10 with custom CSS (I believe this works the same way on a clean Joplin install).
The interface font size is 14.

![2020-12-29 19_50_13-](https://user-images.githubusercontent.com/27277781/103300094-fe77a080-49f5-11eb-81f4-01806336d061.png)

**Comment by cqroot** [comment]
I will add a setting page to support appearance customization.

**Comment by cqroot** [comment]
Now you can set the font, color and font size on the settings page. Settings will be applied when you refresh the outline panel (such as switching notes).
