### ISSUE TITLE
Headings with html tags and maths are incorrectly displayed and don't work as liks

### ISSUE THREAD

**Issue by ken1kob** [cqroot/joplin-outline#35]
As follows, headings with html tags and headings with math expressions are incorrectly displayed. Besides, they do not work as clickable internal links.

![jopline-outline-bug2](https://user-images.githubusercontent.com/16041683/120574258-f1098b00-c459-11eb-8f31-941bf2a2fcac.PNG)

They should be displayed as follows in the OUTLINE panel. Html tags should be removed, but their contents should be remained. Math expressions and their contents should be removed.

    Heading1
    Heading2 with html
    Heading3 with math

**Comment by ken1kob** [comment]
The following is an example code fixing this bug.

```javascript
        // check header
        line = line.replace(/\s+#+\s*$/, '');

        // START OF EXAMPLE
        // remove HTML elements
        while (true) {
            let x = line.replace(/<.*?>([^<>]*?)<\/.*?>/, '$1');
            if (x == line) break
            line = x
        }
        // remove math
        while (true) {
            let x = line.replace(/\$[^\$]+\$/, '');
            if (x == line) break
            line = x
        }
        // END OF EXAMPLE

        const match = line.match(/^(#+)\s(?:\[(.*)\]|(.*))/);
```

**Comment by Edwardlin-zlt** [comment]
@ken1kob How did you put the outline to the left side?~~

**Comment by cqroot** [comment]
> @ken1kob How did you put the outline to the left side?~~

Menu: View -> Change application layout
