### ISSUE TITLE
Incremental searching is sometimes resetted

### ISSUE THREAD

**Issue by ken1kob** [cqroot/joplin-outline#36]
This bug happens in the limited situation that the OUTLINE panel is below the notelist panel at the bottom as follows (it's my favorite layout, since OUTLINE cannot be placed at the right end).
In the search box in the notelist panel, when you are searching some text and no candidate notes are found, the OUTLINE panel is hidden (it's OK) and **the text in the searching box is vanished (it's a BUG).** So, searching is often unusable and very frustrating.

![jopline-outline-bug3](https://user-images.githubusercontent.com/16041683/120576213-6165db80-c45d-11eb-9e35-0d13775809e0.PNG)

Although I'm not sure how to fix this problem, I think the cause is that hiding the OUTLINE panel affects the notelist and its search box.

**Comment by ken1kob** [comment]
There is a simple workaround. If hiding the OUTLINE panel can be disabled with a option (that is, empty toc can be displayed), change event of the layout of panels does not happen and the bug can be avoided.

In point of UI view, keeping the panel displayed may be natural, because I feel some confused when the OUTLINE panel occationally appears and disappears depending on the content of notes.

**Comment by cqroot** [comment]
![image](https://user-images.githubusercontent.com/46901748/122667155-fa2d8280-d1e3-11eb-84ad-6de403554059.png)

Version 1.2.2 supports it.
