### ISSUE TITLE
css selectors to style the appearance?

### ISSUE THREAD

**Issue by lucker999** [cqroot/joplin-outline#37]
Hi, thank you for the awesomely helpful plugin! Can't live without it!

Is it to much to ask to at least list somewhere (here, on guthub description page, wherever) the css classes of the TOC in sidebar? As I understand, if I add some style in `userchrome.css`, the plugin catches it, right? I mean, to adjust the margins or padding. I love the TOC, but some of my notes a quite long. This deprives me to see the entire TOC at a glance, need to scroll it. 

I also would like to make each level of a different style, for instance. And some more, but can't find the selectors I need to use.

Thanks again.

**Comment by andrei-a-papou** [comment]
I've styled the plugin's iframe to remove the bottom border and increasing the padding. But it seems that things _inside_ the iframe can't be styled via userchrome.css. 

Would love the ability to style the OUTLINE header, for example, to match the rest of my theme!

**Comment by placoderm** [comment]
I believe this is a Joplin limitation. That's why you see plugins like this putting style option in the settings.

**Comment by cqroot** [comment]
Now you can customize css in the "userStyle" item in the settings.

**Comment by placoderm** [comment]
Hello! Thanks for adding this!

I can't figure out how it works, though. I tried this:
![image](https://user-images.githubusercontent.com/31570884/144784248-de10e621-b992-4608-ad15-f3d487d7fdd9.png)

but after reloading Joplin (not sure if that is needed) the text of the outline is still black. I also tried adding `!important` but that didn't help.

What am I doing wrong?

**Comment by cqroot** [comment]
https://github.com/cqroot/joplin-outline/wiki/Custom-panel-style
I just wrote an example.

**Comment by placoderm** [comment]
Ah, awesome. I got confused because of the number style above it.

Small suggestions... It might make more sense as a larger text input box if that is possible. Also, I have seen similar situations where for something like this a new install might include the following pre entered in the field:
```css
#header {
 
}

.toc-item-link {
  
}

.toc-item-link:hover {
 
}
```

Thanks for the great plugin! Honestly I think it deserves to be in core.
