### ISSUE TITLE
Remember the toggle status

### ISSUE THREAD

**Issue by qrsp** [cqroot/joplin-outline#38]
Hello, thank you for making this plugin lets me get rid of the `[TOC]` that messed up the alignment.
But I found every time I restart Joplin, the outline panel toggled.
Could you add a setting for toggling on/off the panel at startup or remember the toggle status when close Joplin?

**Comment by giantrule** [comment]
I have a same comment with you. And please save the last size of Outline panel. At startup, it take much space than the note content page.

**Comment by qrsp** [comment]
@giantrule  About the panel size is a [Joplin bug](https://github.com/cqroot/joplin-outline/issues/27). I followed cqroot's instruction put the outline on the left side of the note

**Comment by andrei-a-papou** [comment]
Confirming this. The plugin is very useful to me, but I need to toggle it, and due to this bug it's only usable if placed between the notes list and the editor column.

**Comment by micmalti** [comment]
This became an issue for me after the upgrade to v3. Is there a workaround besides changing the order placement of the panel?
