### ISSUE TITLE
Enable jump to editor layout heading

### ISSUE THREAD

**Issue by tsonne** [cqroot/joplin-outline#39]
I'm only using the Editor layout in Joplin (have disabled rendered PDF layout via plugin https://github.com/JJ-8/joplin-disable-pdf).

When clicking a heading in the Outline, nothing happens in that case. Is it possible to make a jump to an Editor position instead of to a preview/PDF position? It would be an enhancement for Editor-only users.

**Comment by cqroot** [comment]
1.2.5 version already supported.

**Comment by tsonne** [comment]
Great, works like a dream now!
Finally huge documents can be navigated very quickly in joplin while having PDF preview disabled.
Thanks a lot, this issue can be closed now.
