### ISSUE TITLE
Add "Table of Contents" into the description

### ISSUE THREAD

**Issue by placoderm** [cqroot/joplin-outline#46]
I noticed on the forum that many people refer to this plugin as the "table of contents plugin." However searching for that term in the plugin interface returns nothing. I'm not suggesting that the name of the plugin be changed, but adding the term into the description might help people find it.

Thanks for the great plugin!

**Comment by cqroot** [comment]
Thanks for your advice. I added the `TOC` keyword in the plugin description.
