### ISSUE TITLE
Use rendered text as outline content

### ISSUE THREAD

**Issue by Edwardlin-zlt** [cqroot/joplin-outline#47]
![image](https://user-images.githubusercontent.com/35733429/136651986-ae7833ae-b29b-472a-964f-31c754b5bcd0.png)

## Description

The screenshot is a note that I imported by using joplin web clip. The Heading's have anchor which will not display in rendered contents. 

But `Outline` plugin use markdown version as its title content, which would be better to use clean word like the rendered contents.

**Comment by gustavklopp** [comment]
and it would be great to render Katex formula also.
