### ISSUE TITLE
Titles are not recognized when there is a bulleted list

### ISSUE THREAD

**Issue by special0star1** [cqroot/joplin-outline#49]
1.Titles are not recognized when there is a bulleted list.
2.There is an error in title recognition when there is an html tag.
3.Want the # tag to be recognized as a title regardless of where it is located.
![image](https://user-images.githubusercontent.com/92930690/139391470-b7d5f35e-8d1c-4945-881d-cc9c1b758106.png)
@cqroot

**Comment by cqroot** [comment]
I think it is normal for titles in bulleted list not to be recognized.

This is also the case in [typora](https://typora.io/).

![image](https://user-images.githubusercontent.com/46901748/195986413-30d65763-fdc3-4990-a295-37dcd6a085e1.png)
