### ISSUE TITLE
Joplin Theme

### ISSUE THREAD

**Issue by deciacco** [cqroot/joplin-outline#5]
This is really a great plugin! Thank you! Should have been in Joplin since the beginning, but now with the Plugins feature at least it will be available and probably one of the most installed!

I'd like to submit a feature request that the TOC take on the theme selected in the Joplin settings...

Thanks again!

**Comment by cqroot** [comment]
Currently, the background color and font of the outline follow the theme by default, and they can all be set.
The font color was originally green because I liked the color scheme of the vue page. Now I think it should really follow the theme to switch.
And welcome to submit feature requests

**Comment by deciacco** [comment]
hmm... something doesn't seem right... the font is supposed to be Roboto, but it doesn't look the same. I tried to change it in the settings, and I was able to make it white (#ffffff) but font size or style appear to have no effect. This is on 1.5.14 on Ubuntu with XFCE. 

![image](https://user-images.githubusercontent.com/36453844/103418168-216b9700-4b53-11eb-9011-5efaa0a42e82.png)

**Comment by cqroot** [comment]
I don't know if your font name is correct.This is applied directly to css.

For the font size, try 18pt instead of 18. I will default the unit to pt later, just like word.

**Comment by deciacco** [comment]
OK... so using the "pt" worked. Changing the name of the Font did as well. I did not have Roboto installed on my system, and even though the _Web Development Tool_ in Joplin showed _Roboto_ it was probably using Noto. That said, if I leave the defaults, that is `var(--joplin-font-family)` and `var(--joplin-font-size)` it does not match the rest of Joplin which I find odd...

Thanks for the pointers so far...
