### ISSUE TITLE
Deacrease spacing of heading list

### ISSUE THREAD

**Issue by placoderm** [cqroot/joplin-outline#56]
Currently the space between headings in the outline seems to be equal to or greater than the font size

<img src="https://user-images.githubusercontent.com/31570884/143850863-c5af30de-7534-4883-810f-e59ba023a64f.png" height=30% width=30%>

It appears to be set as a margin on `p.toc-item`, but I have looked in the source code and can only find margin once, and it's not for this class.

Using a small laptop, screen space is at a premium, so being able to double the number of items in the list would be really useful.

Not sure what the best solution is. Regular view/compact view?

**Comment by placoderm** [comment]
BTW, Thanks so much for the plugin!!!

**Comment by cqroot** [comment]
Now you can customize css in the "userStyle" item in the settings.
