### ISSUE TITLE
Links in the outline lead to other parts of the document than they should

### ISSUE THREAD

**Issue by lukgreen** [cqroot/joplin-outline#6]
For example, I have a section in the document named '# Part 10'. When I click on a link in an outline, I find myself looking at the '# Part 50' section of the document. I found that the plugin's link puts me 9 sections farther than the one I have clicked on.

**Comment by cqroot** [comment]
Are you in the viewer layout? The pointing position may be inaccurate in the Editor layout.

**Comment by lukgreen** [comment]
Yes. This happens in the editor layout.

**Comment by cqroot** [comment]
Okay, it's normal to have inaccurate positioning in the editor layout. The point is that the preview layout positioning is accurate.
