### ISSUE TITLE
Outline does not work correctly when Note Variables plugin is installed

### ISSUE THREAD

**Issue by petzi53** [cqroot/joplin-outline#64]
There is a conflict with the Note Variables plugin. With the installation of the [Note Variables plugin](https://github.com/DanteCoder/JoplinPluginNoteVariables), your plugin loses its functionality to toggle the visibility of the panel: The Outline panel button (hamburger icon) disappears, and the shortcut F9 does not work anymore.

I have [reported the issue](https://github.com/DanteCoder/JoplinPluginNoteVariables/issues/8) to the Note Variables plugin as well.

**Comment by cqroot** [comment]
I installed the [Note Variables plugin](https://github.com/DanteCoder/JoplinPluginNoteVariables), but the problem does not appear.

**Comment by petzi53** [comment]
I believe that for replication, you must observe the order of turning on the plugins and if the Outline panel was active the last time. You can't test it anymore with the Notes Variables plugin because it has just released a new version with a complete overhaul, so the problem does not happen anymore.  

But I tracked problems of Outline with other plugins as well ([Agenda](https://gitlab.com/beatlink-code/joplin-plugin-agenda), [Convert Text To New Note](https://github.com/ambrt/joplin-plugin-create-note-from-text) and [Menu Shortcut Toolbar](https://github.com/tessus/joplin-plugin-menu-shortcut-toolbar#readme)).  You can see the problem also in the list of keyboard shortcuts.  It says `toggleOutline (Invalid)`. See image.

![image](https://user-images.githubusercontent.com/24394304/180861186-06210bca-d25d-4f8f-ae4e-7af95b4fc7a6.png)

But as I said, tracking the exact problem is complex. Sometimes it works in a certain configuration; many times, it does not.

**Comment by joochlee** [comment]
> I believe that for replication, you must observe the order of turning on the plugins and if the Outline panel was active the last time. You can't test it anymore with the Notes Variables plugin because it has just released a new version with a complete overhaul, so the problem does not happen anymore.
> 
> But I tracked problems of Outline with other plugins as well ([Agenda](https://gitlab.com/beatlink-code/joplin-plugin-agenda), [Convert Text To New Note](https://github.com/ambrt/joplin-plugin-create-note-from-text) and [Menu Shortcut Toolbar](https://github.com/tessus/joplin-plugin-menu-shortcut-toolbar#readme)). You can see the problem also in the list of keyboard shortcuts. It says `toggleOutline (Invalid)`. See image.
> 
> ![image](https://user-images.githubusercontent.com/24394304/180861186-06210bca-d25d-4f8f-ae4e-7af95b4fc7a6.png)
> 
> But as I said, tracking the exact problem is complex. Sometimes it works in a certain configuration; many times, it does not.

same here, after upgrading it does not work anymore. 
I am using following plugins:
- admonition markdown extension
- combine notes
- menu items, shortcuts, toolbar icons
- note tabs

so I downgraded to 1.3.1.
1.3.1 still works

**Comment by cqroot** [comment]
Does the problem still exist in 1.4.2?

Sorry I still can't reproduce this problem. I tried removing the default keybindings and redundant plugin settings.
