### ISSUE TITLE
Not Work with Windows Jopin 2.8.8

### ISSUE THREAD

**Issue by telnetning** [cqroot/joplin-outline#65]
There is only a word "outline" in the outline panel.

![image](https://user-images.githubusercontent.com/1511067/188198431-ce344030-a374-4fe1-9d61-26a55ca11d5f.png)

Windows 11 + Joplin 2.8.8, sorry for I cannot find why it does not work and hope someone can help me.

**Comment by cqroot** [comment]
Sorry it's a bug due to the 1.4.0 update, I'll fix it later.

**Comment by cqroot** [comment]
1.4.1 has been released with this bug fixed.

The [plugin repository](https://github.com/joplin/plugins) will be automatically updated in the next update cycle. It is updated every 30 minutes on the hour and half-hour.

Or you can download the jpl file from [github release](https://github.com/cqroot/joplin-outline/releases) and install it manually.

**Comment by telnetning** [comment]
Thank you for such a quick reply and work. I updated and it works now!
