### ISSUE TITLE
[Question] - The space between two sections is a little wide

### ISSUE THREAD

**Issue by dunmorogher** [cqroot/joplin-outline#67]
Hello there!
Can anyone guide me how to reduce the space size between two sections in outline area?

![image](https://user-images.githubusercontent.com/41850822/189107058-550a9f57-92af-48be-8bdb-5f3e22d9c554.png)

Thanks a lot in advance! :-)

**Comment by cqroot** [comment]
```css
div.container p {
  margin: 5px;
}
```

Add it to `User Style` in plugin settings or `$profileDir/outline.css`.

https://github.com/cqroot/joplin-outline/wiki/Custom-panel-style

**Comment by dunmorogher** [comment]
> ```css
> div.container p {
>   margin: 5px;
> }
> ```
> 
> Add it to `User Style` in plugin settings or `$profileDir/outline.css`.
> 
> https://github.com/cqroot/joplin-outline/wiki/Custom-panel-style

@cqroot thanks for this! And if you can tell me where is the folder path of `$profileDir`? :-)

**Comment by cqroot** [comment]
The directory can be accessed from the menu `Help` - `Open profile directory`

**Comment by dunmorogher** [comment]
@cqroot got it! Thank you!

**Comment by dunmorogher** [comment]
@cqroot Hi, I put the CSS code into userstyle.css, but it seemed still not working.

![image](https://user-images.githubusercontent.com/41850822/189268117-3813d105-82b6-475a-8f07-482bbeec8e36.png)

![image](https://user-images.githubusercontent.com/41850822/189268124-6285a950-4c34-40b1-95df-7040112f45a2.png)

**Comment by cqroot** [comment]
Add in `outline.css` instead of `userstyle.css`.

**Comment by dunmorogher** [comment]
When I clicked the "Open profile directory" it said below:

![image](https://user-images.githubusercontent.com/41850822/189279343-e79d3290-254e-4841-864c-941a25d75538.png)

So, should I manually create that file in the directory that the screenshot mentioned?

By the way, it is actually not working to add the CSS code into "userstyle.css", is that right? Or the Wiki content should be changed? :-)

**Comment by cqroot** [comment]
1. The `user style` in the wiki refers to the plugin settings
2. I don't know why the profile directory does not exist. Generally, this is the directory where `userstyle.css` is located.

![image](https://user-images.githubusercontent.com/46901748/189281084-fc632590-39c5-4bbe-9efa-a9c3fa754863.png)

**Comment by dunmorogher** [comment]
Cool! I put the code into the location as your screenshot points to and then it works as expected. For "Open profile directory" I got it.
Thank you again!
