### ISSUE TITLE
the key binding is removed, how to add it? 

### ISSUE THREAD

**Issue by dantezhu** [cqroot/joplin-outline#68]
hi, it's a good plugin.

But it seems that the key binding is removed in the latest version, how to add it by myself?

as you mentioned:

> You can configure it on the Keyboard shortcuts page.

but it seems I could not find this configuration, I am using Mac.

![image](https://user-images.githubusercontent.com/1105212/189181720-d753d611-41ba-4935-ae58-0283b1dd0075.png)

#66

**Comment by cqroot** [comment]
Did you try searching for `Toggle outline`?

It works fine on both windows and linux.

![image](https://user-images.githubusercontent.com/46901748/189184122-760b0761-6288-4e83-a60d-a87c06c3a40b.png)

**Comment by dantezhu** [comment]
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/1105212/189184871-94dc86d8-dee5-4bbf-97f1-b7d08b9b7ef1.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/1105212/189184910-3d122268-fc93-47a4-b220-12d229709668.png">


seems not work..

**Comment by cqroot** [comment]
I don't even know what caused this.

Can you try to re-enable the plugin, if it still doesn't work, I will test it on macos tomorrow.

**Comment by dantezhu** [comment]
hi, sorry for late because of sleeping.
I try to disable and enable the plugin, and restart joplin, but it does not work either.

below is versions:
```
MacOS 12.5.1
Joplin 2.8.8
Outline v1.4.2
```

**Comment by cqroot** [comment]
1. Open the command palette (Default shortcut ctrl+shift+p), can you search for `toggleOutline`?

![image](https://user-images.githubusercontent.com/46901748/189298102-f32a7f84-ca29-4faa-a8e7-b4de71190247.png)

2. Does `menu: Tools->outline->Toggle outline` exist?

![image](https://user-images.githubusercontent.com/46901748/189297994-9758cf4f-a139-4085-ac4f-692492b1d8d5.png)

**Comment by dantezhu** [comment]
yes, here it is.
<img width="385" alt="image" src="https://user-images.githubusercontent.com/1105212/189299008-5b61bc49-be85-4f57-9851-bdbed94b6c7d.png">
<img width="607" alt="image" src="https://user-images.githubusercontent.com/1105212/189299048-e63e205c-5965-41c5-bd0e-346a4cce95ed.png">

**Comment by cqroot** [comment]
1.4.3 fixed it.

**Comment by dantezhu** [comment]
cool, it works now, thanks a lot!
