### ISSUE TITLE
Position in the outline is reset after clicking a link

### ISSUE THREAD

**Issue by lukgreen** [cqroot/joplin-outline#7]
For example, I have a document with 100 sections. I scroll down the outline to the bottom and click on a link referring to section 100. The outline looses the position I have scrolled to and if I want to click on a link to section 90, I have to scroll down again.

**Comment by cqroot** [comment]
[1.0.4](https://github.com/cqroot/joplin-outline/releases/tag/1.0.4) fixed this bug.
