### ISSUE TITLE
Heading with double underscores will not navigate

### ISSUE THREAD

**Issue by zhaowei9** [cqroot/joplin-outline#71]
I found in the rich text editor, if I click on a heading with double underscores (e.g. "\_\_get\_\_"), I am not navigated to the corresponding section.
No such a issue in the markdown editor, though.

joplin v2.8.8 on windows.
outline v1.5.2

Thanks.

**Comment by cqroot** [comment]
I tested it works fine in editor, viewer and rich text editor.
Can you provide me with more information?

![2022-11-08 20-32](https://user-images.githubusercontent.com/46901748/200566018-232b78a6-c8a6-4108-ab63-df64ed58ed7a.gif)

joplin v2.8.8 on linux.
outline v1.5.2

**Comment by cqroot** [comment]
I fixed this problem in the new version.

Update the plugin to 1.5.3 and try again.
