### ISSUE TITLE
Headings are not picked up after a one-line code snippet

### ISSUE THREAD

**Issue by n8willis** [cqroot/joplin-outline#73]
This may be related to #34, but it's not quite the same in my experience.

Issue is that a one-line "code block" , for example:
# heading 1
plaintext
```one line 3ticks```
breaks recognition of all subsequent headings. "heading 1" appears in the outline, but no headings after the "one line 3ticks" do.

However, in testing this I discovered that this bug is triggered ONLY when the one-line code block is the first such wrapper encountered. If you change it to 
# heading 1
plaintext
`inline one-tick`
```one line 3ticks```

then the full outline reappears as it should be.

**Comment by cqroot** [comment]
Thanks for your feedback. Try updating the plugin to 1.5.5 and the problem should have been resolved.

**Comment by n8willis** [comment]
Looks good!

Sorry for being slow to replay; just $otherstuff.

Thanks for taking the time; I appreciate it.
