### ISSUE TITLE
Being able to generate an inner link to a section of a document

### ISSUE THREAD

**Issue by lukgreen** [cqroot/joplin-outline#8]
I often make inner links in documents ([section name](#section-name) as well as links to other documents ([name of the document](:/da769492fd9f42a59e3d16687125d044)). To make a link to another document I can click that document's name and choose 'Copy Markdown link' option. I think it would be great to have such an option in the document outline.

**Comment by cqroot** [comment]
1.0.5 now supports right-click to paste markdown inner link.
