### ISSUE TITLE
Feature request: Link to "Top"

### ISSUE THREAD

**Issue by zblesk** [cqroot/joplin-outline#80]
Currently, there is no easy way of going to the top of the document, before any headings. 
I don't want to add a heading at the start of each note, because it would just superfluously restate the note title above it. 

I'd like the Outline to have a visually (de-emphasised?) 'top' link as the first item. Right-clicking it could then copy the link to the note proper.

**Comment by cqroot** [comment]
You can click `OUTLINE` at the top, and it will move the document to the top.

Does this meet your needs? Feedback is always welcome.

**Comment by zblesk** [comment]
OMG, how have I never tried that?! 
Sorry about that. 😅 

Yes, that's sufficient. It would be even better if right-click copied a link to the note, but if you're not planning on adding that, feel free to close the issue. 

Thank you.

**Comment by cqroot** [comment]
Sorry, I don't quite understand what you mean by copy link. Now right-clicking the header in the outline panel will copy the corresponding internal link. Not sure if this meets your needs.

**Comment by zblesk** [comment]
It works for the headings, but when I tried right clicking the word OUTLINE doesn't copy anything.

**Comment by cqroot** [comment]
The feature you mentioned may be the same as the feature of right-clicking notes -> `Copy Markdown link`. Does `Copy Markdown link` meet your requirements?

**Comment by zblesk** [comment]
That's not quite what I want; there are multiple issues. Besides being slower to do, when I'm clicking around the links, Joplin doesn't track the note reliably in the note list. (I.e. i have a note open that I don't see in the note list and therefore can't right click it.)
When that happens, I have to search for the note to copy the link. 

I'd appreciate if the link were reliably available in the same easy-to-access place- in the outline, where the rest of the links are anyway.

**Comment by cqroot** [comment]
Does version 1.5.10 meet your needs? Feedback is always welcome.

**Comment by zblesk** [comment]
Yes. Excellent. Thank you!
