### ISSUE TITLE
Outline panel strange resizing

### ISSUE THREAD

**Issue by kschmid** [cqroot/joplin-outline#83]
While working typically I sometimes resize the Joplin window. 
If I do so, it is mostly the editor and the preview that change. However, since installing Outline, the Outline panel size fluctuates wildly when resizing. Hence, I basically always need to resize the panel width after resizing the window. 

Expected behavior: 
either fixed width of panel or panel resizes in proportion to total window resizing.  
(If this would be easier with a panel on the left side of the editor, I would also welcome this.)

**Comment by joochlee** [comment]
> 

Hi, have you tried to place outline panel to the left side of editor?
outline panel on the left side of joplin editor is not affected while resizing joplin window. 

I hope this tip helps. :smile:

**Comment by kschmid** [comment]
Thanks a lot. This was my mistake. I was not aware that a complete relayout is possible. Indeed, when putting it on the left, it just works ;-)

**Comment by shellspicker** [comment]
Yes, if the outline panel at right-most position, drag panel edge to resize, then toggle panel, you can see that panel auto resize to default width. And the default width is too large, to avoid that, open menu about view change, can move outline panel to left position. After move, outline panel will not change size when toggle it.
By the way, I try to modify the css, but not useful.

**Comment by m2acgi** [comment]
@shellspicker How to move outline panel to left? Thanks.

**Comment by shellspicker** [comment]
> @shellspicker How to move outline panel to left? Thanks.

That's easy, it's a option for panel move, you can find it in menu.

**Comment by m2acgi** [comment]
@shellspicker I've found it, thanks.
