### ISSUE TITLE
Inline blockquote breaks Outline

### ISSUE THREAD

**Issue by silopolis** [cqroot/joplin-outline#85]
Hi,

First thanks for coding and sharing this much needed feature :pray: 

Using Joplin to take coding notes, I often have inline code in titles. Sadly, this messes up the entries rendering as shown in capture, and then breaks it completely if I click on the entry broken entry. No option then than to restart Joplin to recover :/

Take care
J

![Joplin-Outline-Screenshot_20230929_091237](https://github.com/cqroot/joplin-outline/assets/414540/c6101c9e-1801-45a0-9719-f7e63bdbe57a)

**Comment by cqroot** [comment]
Can you provide me with a sample note for reproduction?

**Comment by silopolis** [comment]
Hi,
Of course! Here is the content of the note from the previous capture:

```md
When we refer to **multiprocessing**, we mean the ***simultaneous** execution of processes*.
This is called **parallel programming**.

The execution of the processes is thus *distributed between the processor cores*, which are therefore executed separately and simultaneously.

## [Multiprocessing in Python | Python for DevOps](:/5742cdcd456a4bf2bc7ffc6efad5fadc)

## [`multiprocessing` — Process-based parallelism — Python 3.11.5 documentation](:/3f370f9a8c344c42aa1804646f9d8ffe)

from [Concurrent & Parallel Programming | Python for DevOps](:/13bc076ec22342d2891455a408a912a9)
```

Thanks for caring, have a nice week :)

**Comment by cqroot** [comment]
1.5.13 fixed it.
