### ISSUE TITLE
Text wrap in editor is broken when Outline is active

### ISSUE THREAD

**Issue by rsau** [cqroot/joplin-outline#9]
Hi cqroot

I came across a bug where text wrap is broken in editor when Outline plugin is active. 
It is happening on both  Windows and Ubuntu Appimage versions. 

Steps to reproduce
- Enable Outline plugin
- Make sure only editor is active in layout
- copy and paste following line  in editor
 ```
Joplin - an open source note taking and to-do application with synchronization capabilities for Windows, macOS, Linux, Android and iOS. Forum: Joplin - an open source note taking and to-do application with synchronization capabilities for Windows, macOS, Linux, Android and iOS. Forum:
```

- Maximise Joplin window
- Start resizing the window. Text doesn't wrap if Outline in enabled. 
- Perform above steps again after disabling Outline and text behave as it should. 

Joplin version info 
```
Joplin 1.5.14 (prod, win32)

Client ID: 30a9a553f23a4f9aa0a355d5212c95b7
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: 9e076bf19 (master)
```

Outline version: 1.0.5

Let me know if more details are needed.

**Comment by cqroot** [comment]
Are you encountering this problem：

https://github.com/laurent22/joplin/issues/4238

This is a known bug, waiting for joplin to fix.

**Comment by rsau** [comment]
Yeah, that is exactly the bug but it started happening once I installed Outline so I thought it must be related to plugin and not core app.

**Comment by cqroot** [comment]
This is a problem with the resize strategy caused by the plugin panel. It is because joplin's resize strategy does not consider the plugin panel well. I simply created the plugin panel, and I have no permission to make other changes.

**Comment by rsau** [comment]
Thanks for explanation and plugin. 
Closing the issue as it is not related to Outline.
